-- The fields introduced here were incorporated into the idempotent baseline
-- migration 0006 before the hosted migration ledger was enabled.
-- Intentionally left as a no-op so existing production data remains intact.
