export const israelMarketCopy: Record<string, string> = {
  heroEyebrow: "SPAPLUS מגיעה לישראל",
  heroTitle: "יותר אורחים מחפשים חוויית ספא. בואו נדאג שימצאו אתכם.",
  heroLead: "SpaPlus מקימה בישראל פלטפורמה ייעודית לגילוי ולהזמנה של חוויות ספא. אנחנו מזמינים בתי ספא מבוססים להצטרף לקבוצת השותפים הראשונה ולבנות איתנו ערוץ הזמנות חדש.",
  heroDisclosure: "התמונה משמשת להמחשת הקמפיין בלבד. היא אינה מציגה בית ספא ישראלי או שותף קיים בישראל.",
  seoTitle: "SpaPlus ישראל | שותפים מבתי ספא",
  seoDescription: "SpaPlus בונה בישראל ערוץ ייעודי לגילוי ולהזמנה של חוויות ספא, ומזמינה בתי ספא מבוססים להציג את העסק לבדיקת התאמה.",
  seoImageAlt: "המחשת קמפיין SpaPlus. אינה מציגה בית ספא ישראלי או שותף קיים.",
  referenceMarketName: "SpaPlus קנדה",
  marketDisplayName: "ישראל",
  navAria: "ניווט שותפי SpaPlus ישראל",
  growthCardOneBody: "הציגו את בית הספא כבר עכשיו, כדי שנוכל להכיר את העסק ולבחון התאמה לקבוצת השותפים הראשונה בישראל.",
  platformPreviewTitle: "חוויות ספא ברחבי ישראל",
  platformDisclosure: "המסכים המוצגים הם המחשה של חוויית המוצר. מאגר בתי הספא בישראל עדיין אינו פעיל, והכלים הסופיים עשויים להתעדכן לפני ההשקה.",
  proofTitle: "כך נראית חוויית SpaPlus שכבר פועלת בקנדה.",
  proofIntro: "הדוגמאות הבאות מוצגות כיום בפלטפורמת SpaPlus קנדה. הן ממחישות את סוג החוויה שאנחנו בונים גם עבור הקהל ובתי הספא בישראל.",
  proofDisclosure: "התמונות נלקחו מרשומות פעילות באתר הרשמי של SpaPlus קנדה. הן מציגות בתי ספא בקנדה ואינן מציגות מועמדים או שותפים קיימים בישראל.",
  partnerFitTitle: "בתי ספא ישראליים שמאמינים שחוויית האורח מתחילה הרבה לפני הטיפול.",
  formEyebrow: "פניית שותפות ל־SPAPLUS ישראל",
  formTitle: "בואו נכיר את בית הספא שלכם.",
  formIntro: "השאירו את פרטי העסק פעם אחת. נבדוק את ההתאמה ונחזור אליכם לשיחה עניינית בתוך 72 שעות.",
  formCityLabel: "עיר או יישוב בישראל",
  formSpaTypePlaceholder: "בחירת סוג בית הספא",
  formLocationsPlaceholder: "בחירת מספר סניפים",
  formPreferredContactPlaceholder: "בחירת דרך התקשרות",
  formSubmitButton: "שליחת פרטי בית הספא",
  faqLaunchQuestion: "האם SpaPlus כבר פעילה בישראל?",
  faqCostAnswer: "לא. הצגת בית הספא אינה כרוכה בתשלום, ואיננו מבקשים תשלום או פרטי כרטיס אשראי.",
  finalEyebrow: "ישראל, הגיע הזמן לגלות ספא אחרת",
  finalTitle: "בית הספא שלכם יכול להיות חלק מקבוצת השותפים הראשונה של SpaPlus בישראל.",
  footerIntro: "SpaPlus מקימה בישראל פלטפורמה ייעודית לחוויות ספא. עמוד זה מיועד לבתי ספא מבוססים שמעוניינים להיבחן כשותפים הראשונים בשוק הישראלי.",
  footerTagline: "מגלים. בוחרים. מזמינים. נרגעים.",
  successTitle: "תודה, פרטי בית הספא אצלנו.",
  successBody: "שלחנו אישור בדוא״ל. נבדוק את הפנייה וניצור קשר בתוך 72 שעות.",
  "Required": "חובה",
  "Optional": "לא חובה",
  "Missing:": "חסרים פרטים:",
  "Skip to main content": "דילוג לתוכן הראשי",
  "Refresh this SpaPlus page": "רענון עמוד SpaPlus ישראל",
  "Close navigation": "סגירת התפריט",
  "Open navigation": "פתיחת התפריט",
  "The platform": "הפלטפורמה",
  "How it works": "איך זה עובד",
  "Questions": "שאלות נפוצות",
  "Join early access": "הצטרפות מוקדמת",
  "Market": "שוק",
  "Language": "שפה",
  "Registration terms": "עקרונות ההצטרפות",
  "Spa businesses only": "לבתי ספא פעילים בלבד",
  "Commission only on confirmed SpaPlus bookings": "עמלה רק על הזמנות SpaPlus שאושרו",
  "No monthly fee or extra costs": "ללא דמי מנוי או עלויות נוספות",
  "No long-term commitment": "ללא התחייבות ארוכת טווח",
  "Join the Founding Spa List": "להציג את בית הספא",
  "See SpaPlus in action": "לראות את SpaPlus בפעולה",
  "Registration is an expression of interest. It is not a contract or a purchase.": "הפנייה מביעה עניין בלבד. היא אינה חוזה ואינה רכישה.",
  "Launch status": "מצב הפעילות",
  "LIVE TODAY": "פעיל היום",
  "COMING NEXT": "היעד הבא",
  "A STRONGER WAY TO GROW": "ערוץ צמיחה שנבנה במיוחד לספא",
  "The SpaPlus guest journey": "הדרך של האורח ב־SpaPlus",
  "Discover": "מגלים",
  "Compare": "משווים",
  "Book": "מזמינים",
  "Better spa experiences for guests. New opportunities for Ontario spas.": "לאורחים קל יותר למצוא את החוויה הנכונה. לבתי הספא נפתח ערוץ הזמנות חדש.",
  "SpaPlus brings discovery, offers and booking into one focused spa platform. Guests get a simpler way to find an experience worth making time for. Spa partners get a new channel designed around the way spa businesses actually work.": "SpaPlus מחברת במקום אחד בין השראה, בחירת חוויה והזמנה. האורחים מבינים מה מתאים להם, ובתי הספא מקבלים נוכחות מדויקת ודרך מעשית לנהל ביקוש חדש.",
  "Join before the launch": "להיות בין הראשונים בישראל",
  "Get discovered by new guests": "להגיע לאורחים שמחפשים ספא",
  "Present the experiences, packages and occasions that make your spa worth choosing.": "להציג לא רק טיפול, אלא את החבילות, המתקנים והרגעים שבגללם כדאי לבחור דווקא בכם.",
  "Review the offer before deciding": "להכיר את המודל לפני שמחליטים",
  "If the fit is right, we will explain the launch offer and next steps. You decide whether to continue.": "אם תימצא התאמה, תקבלו את הצעת ההשקה ואת התנאים בכתב. רק אז תחליטו אם נכון להתקדם.",
  "THE FOUNDING PARTNER ADVANTAGE": "היתרון של השותפים הראשונים",
  "A clear path from first conversation to new bookings.": "משיחה ראשונה ועד הזמנות חדשות, בדרך ברורה.",
  "There is no fee to join the early list. We prepare the opportunity together, explain the written launch terms and move forward only if the fit makes sense.": "הצגת בית הספא אינה כרוכה בתשלום. נבין יחד מה נכון לעסק, נציג את התנאים בכתב ונתקדם רק אם יש התאמה אמיתית.",
  "Register free": "מציגים את העסק ללא עלות",
  "No payment or card": "בלי תשלום ובלי כרטיס אשראי",
  "Build the right offer": "בונים הצעה שקל להבין",
  "Profile, packages and fit": "פרופיל, חבילות והתאמה לקהל",
  "Review before launch": "עוברים יחד על הכול",
  "Written terms, no pressure": "תנאים כתובים, בלי לחץ",
  "Grow through bookings": "צומחים מהזמנות בפועל",
  "No booking, no booking commission": "אין הזמנה, אין עמלת הזמנה",
  "ONE SPA PLATFORM": "פלטפורמה אחת לעולם הספא",
  "From first discovery to a confirmed booking.": "מהרגע שבו מתחשק לצאת לספא ועד להזמנה שאושרה.",
  "SpaPlus is being built as a focused home for spa and wellness, not another general marketplace. It gives guests a clear way to choose and gives spa teams a practical way to receive and manage demand.": "SpaPlus אינה עוד אתר כללי עם קטגוריית ספא קטנה. זו פלטפורמה שמתחילה בחוויה שהאורח רוצה ומחברת אותה לבית הספא המתאים, עם כלים שנועדו לעבודה היומיומית של הצוות.",
  "Guest experience": "חוויית האורח",
  "ILLUSTRATIVE PREVIEW": "המחשת ממשק",
  "Find your next good day.": "היום הטוב הבא שלכם מתחיל כאן.",
  "Any date": "כל תאריך",
  "Explore": "לגלות",
  "COUPLES": "לזוגות",
  "A day made for two": "יום שנועד לשניכם",
  "DAY PASS": "כניסה יומית",
  "More than a treatment": "הרבה יותר מטיפול",
  "SOLO RESET": "זמן לעצמי",
  "Time that is entirely yours": "כמה שעות שהן רק שלכם",
  "PARTNER VIEW": "ממשק שותפים",
  "Today at your spa": "היום בבית הספא",
  "LIVE": "פעיל",
  "NEW REQUESTS": "בקשות חדשות",
  "CONFIRMED": "אושרו",
  "Couples spa experience": "חוויית ספא זוגית",
  "2 guests · Confirmation requested": "שני אורחים, ממתינים לאישור",
  "Review": "לבדיקה",
  "Day spa package": "חבילת יום ספא",
  "1 guest · Confirmed": "אורח אחד, ההזמנה אושרה",
  "Ready": "מוכן",
  "A dedicated spa marketplace": "זירה שמתמקדת רק בחוויות ספא",
  "Present treatments, packages, day passes and spa stays in a place where guests arrive specifically looking for wellness.": "הציגו טיפולים, חבילות, כניסות יומיות וחופשות ספא במקום שאליו אנשים מגיעים במיוחד כדי לבחור חוויית וולנס.",
  "Booking requests that are easy to manage": "בקשות הזמנה שקל לנהל",
  "Receive a request by email and in the partner system, then review and confirm it without a complicated process.": "מקבלים בקשה בדוא״ל ובמערכת השותפים, בודקים ומאשרים בלי תהליך מסורבל.",
  "Availability at the level that suits you": "זמינות ברמת החיבור שמתאימה לעסק",
  "Start by confirming requests. Spas that maintain live availability can move toward immediate confirmation.": "אפשר להתחיל באישור ידני של בקשות. בית ספא שמנהל זמינות חיה יוכל להתקדם לאישור מיידי של הזמנות מתאימות.",
  "Clear payments and monthly reconciliation": "תשלומים ודוח חודשי ברורים",
  "Guests may pay online or at the spa, according to the available offer. A monthly report keeps bookings, commission and settlement transparent.": "בהתאם להצעה, האורח משלם מראש או בבית הספא. דוח חודשי מרכז את ההזמנות, העמלות וההתחשבנות בשקיפות.",
  "BUILT FOR REAL SPA EXPERIENCES": "מהשטח, לא מתבנית כללית",
  "THE OCCASIONS PEOPLE MAKE TIME FOR": "הרגעים שבשבילם אנשים מפנים זמן",
  "Not one kind of guest. Not one kind of spa day.": "לא כל אורח מחפש אותו דבר. לא כל יום ספא צריך להיראות אותו דבר.",
  "The platform is designed to help people start with the experience they want, then find a spa that fits.": "החיפוש מתחיל במה שהאורח רוצה להרגיש ולעשות, ומשם מוביל לבית הספא שמתאים לרגע.",
  "For two": "לשניים",
  "Couples experiences, celebrations and time away together.": "חוויות זוגיות, ימי הולדת וזמן משותף מחוץ לשגרה.",
  "For one": "לעצמי",
  "A treatment, a quiet reset or a full day devoted to yourself.": "טיפול, הפסקה שקטה או יום שלם שמוקדש לעצמכם.",
  "For groups": "לקבוצה",
  "Birthdays, friends, teams and occasions worth planning well.": "ימי הולדת, חברות, צוותים ואירועים שכדאי לתכנן כמו שצריך.",
  "For the whole day": "ליום שלם",
  "Day passes, thermal experiences, resort spas and spa stays.": "כניסה יומית, מתקנים, חוויה תרמית, מלון או חופשת ספא.",
  "WHO WE WANT TO MEET": "את מי נשמח להכיר",
  "Day spas with a physical commercial location": "ספא יום שפועל במתחם מסחרי מסודר",
  "Hotel, resort, Nordic and thermal spas": "ספא במלון, באתר נופש או במתחם תרמי",
  "Wellness venues with bookable spa experiences": "מתחמי וולנס שמציעים חוויות שניתן להזמין",
  "Multi-location groups preparing for their next growth channel": "קבוצות ספא עם כמה סניפים שמחפשות ערוץ צמיחה נוסף",
  "Choose an area to open its dedicated partner page. These are campaign targets, not a claim that SpaPlus is already operating there.": "בחרו אזור כדי לעבור ישר לטופס. הרשימה מציגה אזורי גיוס בלבד ואינה טוענת ש־SpaPlus כבר פעילה בהם.",
  "SpaPlus is not currently onboarding individual mobile therapists, home-based services or solo private treatment rooms through this program.": "בשלב זה התוכנית אינה מיועדת למטפלים ניידים, לשירות בבית הלקוח או לחדר טיפולים פרטי של מטפל יחיד.",
  "Priority launch areas": "נשמח להכיר בתי ספא מכל הארץ",
  "A LOCAL LAUNCH WITH A GLOBAL PLATFORM": "השקה ישראלית, פלטפורמה עם ניסיון בינלאומי",
  "Local focus areas": "אזורי פעילות בישראל",
  "A MODEL THAT STARTS SIMPLE": "מתחילים פשוט, מתקדמים לפי הצורך",
  "Understand the journey before you decide.": "הבינו איך המודל עובד, ורק אחר כך החליטו.",
  "The initial partner setup supports booking requests and confirmations. Spas can manage availability in the partner system for immediate confirmation, with deeper calendar connections planned as the market develops.": "בתחילת הדרך אפשר לקבל בקשות הזמנה ולאשר אותן במערכת השותפים. בתי ספא שמנהלים זמינות יוכלו לאפשר אישור מהיר יותר, ובהמשך ניתן יהיה להעמיק את החיבור למערכות הקיימות.",
  "DISCOVERY": "גילוי",
  "Your spa is presented to guests": "בית הספא מוצג לאורחים הנכונים",
  "People can discover your venue, understand your experiences and choose an offer that fits the occasion.": "האורחים מכירים את המקום, מבינים את החוויה ובוחרים הצעה שמתאימה לרגע שלהם.",
  "BOOKING": "הזמנה",
  "You stay in control of confirmation": "השליטה באישור נשארת אצלכם",
  "Confirm from the email or partner system. If you maintain live availability, eligible bookings can be confirmed immediately.": "מאשרים דרך הדוא״ל או מערכת השותפים. כאשר מנוהלת זמינות חיה, הזמנות מתאימות יכולות לקבל אישור מיידי.",
  "PAYMENT": "תשלום",
  "The guest chooses the available payment option": "האורח בוחר בדרך התשלום הזמינה",
  "For pay-at-spa bookings, the spa charges the guest. For prepaid bookings, SpaPlus processes the payment.": "בהזמנה לתשלום במקום, בית הספא מחייב את האורח. בהזמנה ששולמה מראש, SpaPlus מטפלת בתשלום.",
  "SETTLEMENT": "התחשבנות",
  "One clear monthly picture": "תמונה חודשית ברורה במקום אחד",
  "A report shows what was charged, the applicable commission and the net balance to settle between the parties.": "הדוח מציג את ההזמנות, הסכומים שנגבו, העמלה הרלוונטית והיתרה להתחשבנות.",
  "Built to become even easier": "נבנה כך שהעבודה תהפוך לפשוטה יותר",
  "After the initial operating period, deeper calendar connections may allow full availability checks and more bookings to flow through automatically.": "לאחר תקופת ההפעלה הראשונית, חיבורים עמוקים יותר ליומנים עשויים לאפשר בדיקת זמינות מלאה וזרימה אוטומטית של יותר הזמנות.",
  "SIMPLE FROM THE START": "תהליך קצר ומכבד",
  "Four steps. No pressure.": "ארבעה שלבים. בלי לחץ ובלי הפתעות.",
  "The form helps us understand your spa before we speak. It does not create a contract or commit you to joining.": "הטופס עוזר לנו להגיע מוכנים לשיחה. הוא אינו יוצר חוזה ואינו מחייב אתכם להצטרף.",
  "Introduce your spa": "מציגים את בית הספא",
  "Share the basics about your venue, services and location.": "מספרים לנו בקצרה על המקום, השירותים והמיקום.",
  "We review the fit": "בודקים התאמה",
  reviewStepBody: "הצוות שלנו בודק כל פנייה מלאה בתוך 72 שעות.",
  "We compare the business, location and services with the market we are building.": "בוחנים את העסק, המיקום והשירותים מול השוק שאנחנו בונים בישראל.",
  "Have a real conversation": "מקיימים שיחה אמיתית",
  "We explain the launch plan, answer questions and learn more.": "מסבירים את התוכנית, עונים על שאלות ומבינים מה נכון לעסק.",
  "Decide together": "מחליטים יחד",
  "If there is a strong fit, you can review the written launch offer before choosing whether to move ahead.": "אם יש התאמה, עוברים על הצעת ההשקה בכתב ורק אז מחליטים אם להתקדם.",
  "Tell us about your spa.": "בואו נכיר את בית הספא שלכם.",
  "What happens after you send it?": "מה קורה אחרי השליחה?",
  "You receive an immediate email confirmation.": "מקבלים אישור מיידי בדוא״ל.",
  "Our team reviews the business and location.": "הצוות בודק את העסק, המיקום והשירותים.",
  "We contact you to arrange a short conversation.": "יוצרים איתכם קשר לשיחה קצרה וממוקדת.",
  "No payment or card details are requested.": "לא מבקשים תשלום או פרטי אשראי.",
  "Only five business details are required.": "רק חמישה פרטים עסקיים הם חובה.",
  "Business name, contact person, phone, business email and spa location are required and clearly marked below. This form is only for owners, managers and authorized representatives of operating spa businesses. It is not for spa customers, job applicants or unrelated enquiries. Do not submit repeated or irrelevant messages.": "שם העסק, איש הקשר, הטלפון, הדוא״ל העסקי והמיקום הם פרטי החובה. הטופס מיועד לבעלים, למנהלים ולנציגים מורשים של בתי ספא פעילים בלבד.",
  "Spa or business name": "שם בית הספא או העסק",
  "Contact person": "שם איש הקשר",
  "Phone": "טלפון",
  "Business website or Instagram": "אתר העסק או עמוד עסקי",
  "Business address": "כתובת העסק",
  "City or community": "עיר או יישוב",
  "Postal code": "מיקוד",
  "Type of spa": "סוג בית הספא",
  "Number of locations": "מספר סניפים",
  "1 location": "סניף אחד",
  "2 to 3 locations": "שניים עד שלושה סניפים",
  "4 to 10 locations": "ארבעה עד עשרה סניפים",
  "11 or more locations": "אחד עשר סניפים או יותר",
  "Main services offered": "השירותים המרכזיים",
  "Your role": "התפקיד שלכם בעסק",
  "Business email": "דוא״ל עסקי",
  "Preferred contact": "דרך התקשרות מועדפת",
  "Email": "דוא״ל",
  "Current booking system": "מערכת ההזמנות הנוכחית",
  "Anything we should know?": "יש משהו נוסף שכדאי שנדע?",
  "Leave this field empty": "יש להשאיר שדה זה ריק",
  "Privacy confirmation": "אישור פרטיות",
  "Partnership acknowledgement": "אישור פנייה עסקית",
  "I agree that SpaPlus may use these details to assess and respond to this enquiry, as described in the ": "אני מאשר או מאשרת ל־SpaPlus להשתמש בפרטים לצורך בדיקת הפנייה וחזרה אליי, כמפורט ב",
  "Privacy Policy": "מדיניות הפרטיות",
  "I confirm that I own, manage or am authorized to represent an operating spa business that wants more SpaPlus bookings. I understand that SpaPlus charges commission only on confirmed bookings it generates, with no monthly fee, no extra costs and no long-term commitment.": "אני מאשר או מאשרת שאני בעלים, מנהל או נציג מורשה של בית ספא פעיל שמעוניין בהזמנות דרך SpaPlus. ברור לי שהעמלה נגבית רק על הזמנות מאושרות שמגיעות מ־SpaPlus, ללא דמי מנוי, עלויות נוספות או התחייבות ארוכת טווח.",
  "Sending your details...": "שולחים את הפרטים...",
  "Founding partner terms are not guaranteed. Any commercial offer will be shared separately in writing after a fit review.": "קבלה כשותף אינה מובטחת. כל הצעה מסחרית תימסר בנפרד ובכתב לאחר בדיקת התאמה.",
  "Please choose at least one main service.": "נא לבחור לפחות שירות מרכזי אחד.",
  "We could not send your details right now. Please try again in a moment.": "לא הצלחנו לשלוח את הפרטים כרגע. אפשר לנסות שוב בעוד רגע.",
  "THE IMPORTANT QUESTIONS": "השאלות שחשוב לשאול",
  "Before you register.": "לפני שמשאירים פרטים.",
  "Does it cost anything to register?": "האם יש עלות להצגת בית הספא?",
  "Early registration is free. If there is a strong fit, the full launch offer and commercial terms are reviewed with you in writing before any commitment.": "לא. הצגת בית הספא אינה כרוכה בתשלום. אם תימצא התאמה, תקבלו את הצעת ההשקה ואת התנאים המסחריים בכתב לפני כל התחייבות.",
  "Am I committing my spa to join?": "האם הפנייה מחייבת את בית הספא להצטרף?",
  "No. The form only tells us you are interested in learning more. You can review the launch offer before making any decision.": "לא. הטופס רק מאפשר לנו לבדוק התאמה ולחזור אליכם. תוכלו לעבור על ההצעה לפני שתקבלו החלטה.",
  "The launch date has not been announced. Early registrations help us build the right founding group before opening the market.": "מועד ההשקה בישראל עדיין לא פורסם. הפניות המוקדמות עוזרות לנו לבנות את קבוצת השותפים הנכונה לפני פתיחת השוק.",
  "What happens with bookings later?": "איך יתנהלו ההזמנות?",
  "Guests may be offered pay-now or pay-at-the-spa options, depending on the experience. Settlement and commission details are shown in a clear monthly report and explained before a spa goes live.": "בהתאם לחוויה, האורח יוכל לשלם מראש או בבית הספא. פרטי העמלות וההתחשבנות יוצגו בדוח חודשי ברור ויוסברו לפני העלייה לאוויר.",
  "How are guest payments handled?": "איך מטפלים בתשלומי האורחים?",
  "SpaPlus network links": "קישורים לרשת SpaPlus",
  "SpaPlus network": "רשת SpaPlus",
  "SpaPlus Global": "SpaPlus העולמית",
  "SpaPlus Canada": "SpaPlus קנדה",
  "Join SpaPlus in Québec": "הצטרפות ל־SpaPlus בקוויבק",
  "Ontario launch": "השקת אונטריו",
  "Join SpaPlus across Canada outside Ontario": "הצטרפות ל־SpaPlus בשאר קנדה",
  priorityAreasAria: "אזורי גיוס שותפים בישראל",
  priorityAreasTitle: "אזורי גיוס בישראל",
  "Legal and privacy links": "קישורי פרטיות ונגישות",
  "Trust and access": "אמון ונגישות",
  "Accessibility": "נגישות",
  "Management login": "כניסה למערכת הניהול",
  "Cookie settings": "העדפות עוגיות",
  "© 2026 Global Spa Management Ltd. All rights reserved.": "© 2026 Global Spa Management Ltd. כל הזכויות שמורות.",
  "Back to top": "חזרה לראש העמוד",
  "Top": "למעלה",
  "Discover. Book. Relax.": "מגלים. מזמינים. נרגעים.",
  "Close confirmation": "סגירת האישור",
  "YOU’RE ON THE EARLY LIST": "הפנייה התקבלה",
  "Thank you. Your spa details are with us.": "תודה, פרטי בית הספא אצלנו.",
  "Back to the page": "חזרה לעמוד",
  "Privacy choices": "בחירת הגדרות פרטיות",
  "Your privacy, your choice.": "הפרטיות שלכם, הבחירה שלכם.",
  "Essential storage runs the site. Analytics and advertising measurement run only with your permission. Read our ": "אחסון חיוני מפעיל את האתר. מדידה ופרסום יופעלו רק באישורכם. אפשר לקרוא את ",
  "Essential only": "חיוני בלבד",
  "Allow measurement": "אישור מדידה",
  "Day spa": "ספא יום",
  "Hotel or resort spa": "ספא במלון או באתר אירוח",
  "Nordic or thermal spa": "ספא תרמי או נורדי",
  "Medical or wellness spa": "מרכז וולנס או ספא רפואי",
  "Multi-location spa group": "קבוצת ספא עם כמה סניפים",
  "Other established spa venue": "בית ספא מבוסס מסוג אחר",
  "Massage": "עיסויים",
  "Facials and skincare": "טיפולי פנים וטיפוח",
  "Body treatments": "טיפולי גוף",
  "Thermal or Nordic experience": "חוויה תרמית או נורדית",
  "Couples experiences": "חוויות לזוגות",
  "Group experiences": "חוויות לקבוצות",
  "Day passes": "כניסות יומיות",
  "Spa stays": "חופשות ספא",
};

export function israelCopy(key: string, fallback?: string) {
  if (Object.prototype.hasOwnProperty.call(israelMarketCopy, key)) {
    return israelMarketCopy[key];
  }
  return fallback ?? key;
}
