import { env } from "cloudflare:workers";

const runtimeEnv = env as unknown as Record<string, string | undefined>;
const setting = (name: string) => runtimeEnv[name] || process.env[name] || "";
const GRAPH_VERSION = setting("META_GRAPH_VERSION") || "v26.0";
const PAGE_ID = "1065026380020011";
const AD_ACCOUNT_ID = "act_1589838366042003";

const CURRENT_ADS = {
  quebec_en: "120248856435120499",
  quebec_fr: "120248856435130499",
  ontario_en: "120248551862430499",
  ontario_fr: "120248638305830499",
} as const;

type MarketLanguage = keyof typeof CURRENT_ADS;

function clean(value: unknown) {
  return String(value ?? "").trim();
}

function constantTimeEqual(left: string, right: string) {
  const a = new TextEncoder().encode(left);
  const b = new TextEncoder().encode(right);
  const length = Math.max(a.length, b.length);
  let mismatch = a.length ^ b.length;
  for (let index = 0; index < length; index += 1) {
    mismatch |= (a[index] || 0) ^ (b[index] || 0);
  }
  return mismatch === 0;
}

function authorized(request: Request) {
  const expected = setting("META_CAMPAIGN_ADMIN_TOKEN");
  const provided = request.headers.get("x-spaplus-campaign-token") || "";
  return expected.length >= 48 && constantTimeEqual(expected, provided);
}

function pageToken() {
  const token = setting("META_PAGE_ACCESS_TOKEN")
    .replace(/^\uFEFF/, "")
    .trim()
    .replace(/^["']|["']$/g, "");
  if (!token) throw new Error("Meta access token is not configured");
  return token;
}

async function graph(
  path: string,
  method: "GET" | "POST" = "GET",
  params: Record<string, string> = {},
) {
  const url = new URL(`https://graph.facebook.com/${GRAPH_VERSION}/${path.replace(/^\//, "")}`);
  const body = new URLSearchParams({ ...params, access_token: pageToken() });
  if (method === "GET") {
    for (const [key, value] of body) url.searchParams.set(key, value);
    const getResponse = await fetch(url, { headers: { accept: "application/json" } });
    const payload = await getResponse.json().catch(() => ({}));
    if (!getResponse.ok) throw new Error(`Meta GET ${path} failed (${getResponse.status}): ${JSON.stringify(payload).slice(0, 700)}`);
    return payload as Record<string, unknown>;
  }
  const response = await fetch(url, {
    method,
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body,
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(`Meta POST ${path} failed (${response.status}): ${JSON.stringify(payload).slice(0, 700)}`);
  return payload as Record<string, unknown>;
}

const FORM_COPY = {
  quebec_en: {
    locale: "en_US",
    name: "QUEBEC | SPA BUSINESSES ONLY | EN-CA | QUALIFIED V2 | 2026-08-15",
    headline: "Do you operate a spa in Quebec?",
    intro: "For operating spa businesses only. Get more confirmed bookings from SpaPlus. You pay commission only on confirmed bookings generated by SpaPlus. No sign-up fee, no monthly fee, no additional costs and no long-term commitment. Do not submit for personal bookings, jobs, sales pitches or other solicitations.",
    customLabel: "I confirm that I own, manage or represent an operating spa in Quebec and want more bookings from SpaPlus.",
    cityLabel: "City or municipality where your spa is located",
    companyLabel: "Spa business name",
    followUpUrl: "https://app.spaplus.co/en-ca/quebec/",
    thanksTitle: "Thank you. We will review your spa.",
    thanksBody: "SpaPlus will contact authorized spa representatives about the commission-only partnership.",
  },
  quebec_fr: {
    locale: "fr_CA",
    name: "QUEBEC | ENTREPRISES DE SPA SEULEMENT | FR-CA | QUALIFIED V2 | 2026-08-15",
    headline: "Exploitez-vous un spa au Québec?",
    intro: "Réservé aux entreprises de spa en activité. Recevez plus de réservations confirmées grâce à SpaPlus. Vous payez une commission seulement sur les réservations confirmées générées par SpaPlus. Aucuns frais d’inscription, aucuns frais mensuels, aucuns frais supplémentaires et aucun engagement à long terme. Ne soumettez pas ce formulaire pour une réservation personnelle, un emploi, une offre commerciale ou toute autre sollicitation.",
    customLabel: "Je confirme être propriétaire, gestionnaire ou représentant autorisé d’un spa en activité au Québec et vouloir plus de réservations grâce à SpaPlus.",
    cityLabel: "Ville ou municipalité où se trouve votre spa",
    companyLabel: "Nom de l’entreprise de spa",
    followUpUrl: "https://app.spaplus.co/fr-ca/quebec/",
    thanksTitle: "Merci. Nous allons examiner votre spa.",
    thanksBody: "SpaPlus communiquera avec les représentants autorisés de spas au sujet du partenariat à la commission seulement.",
  },
  ontario_en: {
    locale: "en_US",
    name: "ONTARIO | SPA BUSINESSES ONLY | EN-CA | QUALIFIED V2 | 2026-08-15",
    headline: "Do you operate a spa in Ontario?",
    intro: "For operating spa businesses only. Get more confirmed bookings from SpaPlus. You pay commission only on confirmed bookings generated by SpaPlus. No sign-up fee, no monthly fee, no additional costs and no long-term commitment. Do not submit for personal bookings, jobs, sales pitches or other solicitations.",
    customLabel: "I confirm that I own, manage or represent an operating spa in Ontario and want more bookings from SpaPlus.",
    cityLabel: "City or municipality where your spa is located",
    companyLabel: "Spa business name",
    followUpUrl: "https://app.spaplus.co/en-ca/ontario/",
    thanksTitle: "Thank you. We will review your spa.",
    thanksBody: "SpaPlus will contact authorized spa representatives about the commission-only partnership.",
  },
  ontario_fr: {
    locale: "fr_CA",
    name: "ONTARIO | ENTREPRISES DE SPA SEULEMENT | FR-CA | QUALIFIED V2 | 2026-08-15",
    headline: "Exploitez-vous un spa en Ontario?",
    intro: "Réservé aux entreprises de spa en activité. Recevez plus de réservations confirmées grâce à SpaPlus. Vous payez une commission seulement sur les réservations confirmées générées par SpaPlus. Aucuns frais d’inscription, aucuns frais mensuels, aucuns frais supplémentaires et aucun engagement à long terme. Ne soumettez pas ce formulaire pour une réservation personnelle, un emploi, une offre commerciale ou toute autre sollicitation.",
    customLabel: "Je confirme être propriétaire, gestionnaire ou représentant autorisé d’un spa en activité en Ontario et vouloir plus de réservations grâce à SpaPlus.",
    cityLabel: "Ville ou municipalité où se trouve votre spa",
    companyLabel: "Nom de l’entreprise de spa",
    followUpUrl: "https://app.spaplus.co/fr-ca/ontario/",
    thanksTitle: "Merci. Nous allons examiner votre spa.",
    thanksBody: "SpaPlus communiquera avec les représentants autorisés de spas au sujet du partenariat à la commission seulement.",
  },
} as const;

async function createForm(key: MarketLanguage) {
  const copy = FORM_COPY[key];
  return graph(`${PAGE_ID}/leadgen_forms`, "POST", {
    name: copy.name,
    locale: copy.locale,
    block_display_for_non_targeted_viewer: "true",
    allow_organic_lead_retrieval: "false",
    is_optimized_for_quality: "true",
    question_page_custom_headline: copy.headline,
    context_card: JSON.stringify({ title: copy.headline, content: [copy.intro], style: "PARAGRAPH_STYLE" }),
    privacy_policy: JSON.stringify({ url: "https://app.spaplus.co/en-ca/#privacy", link_text: "SpaPlus privacy policy" }),
    questions: JSON.stringify([
      { key: "spa_business_confirmation", type: "CUSTOM", label: copy.customLabel, options: [{ key: "confirmed_spa_business", value: "Yes, I represent an operating spa business" }] },
      { key: "company_name", type: "COMPANY_NAME", label: copy.companyLabel },
      { key: "phone_number", type: "PHONE", label: "Phone number" },
      { key: "full_name", type: "FULL_NAME", label: "Contact name" },
      { key: "email", type: "EMAIL", label: "Business email" },
      { key: "city", type: "CITY", label: copy.cityLabel },
    ]),
    follow_up_action_url: copy.followUpUrl,
    thank_you_page: JSON.stringify({
      title: copy.thanksTitle,
      body: copy.thanksBody,
      button_text: "Visit SpaPlus",
      button_type: "VIEW_WEBSITE",
      website_url: copy.followUpUrl,
    }),
  });
}

async function inspect() {
  const [forms, quebecAds, ontarioAds, account] = await Promise.all([
    graph(`${PAGE_ID}/leadgen_forms`, "GET", { fields: "id,name,status,locale,block_display_for_non_targeted_viewer,is_optimized_for_quality,questions,context_card,thank_you_page,created_time", limit: "100" }),
    graph("120248856435100499/ads", "GET", { fields: "id,name,status,effective_status,adset_id,creative{id,name,object_story_spec,image_hash,thumbnail_url}", limit: "100" }),
    graph("120248551862410499/ads", "GET", { fields: "id,name,status,effective_status,adset_id,creative{id,name,object_story_spec,image_hash,thumbnail_url}", limit: "100" }),
    graph(AD_ACCOUNT_ID, "GET", { fields: "id,name,account_status,currency,timezone_name" }),
  ]);
  return { forms, quebecAds, ontarioAds, account };
}

async function createAd(input: Record<string, unknown>) {
  const key = clean(input.key) as MarketLanguage;
  if (!(key in CURRENT_ADS)) throw new Error("Invalid market/language key");
  const formId = clean(input.formId);
  const imageHash = clean(input.imageHash);
  const message = clean(input.message);
  const headline = clean(input.headline);
  const description = clean(input.description);
  const link = clean(input.link);
  if (!/^\d{10,30}$/.test(formId) || !/^[a-f0-9]{20,80}$/i.test(imageHash)) throw new Error("Invalid form or image");
  if (!message || !headline || !description || !/^https:\/\/app\.spaplus\.co\//.test(link)) throw new Error("Invalid creative copy");
  const oldAd = await graph(CURRENT_ADS[key], "GET", { fields: "id,name,adset_id" });
  const adsetId = clean(oldAd.adset_id);
  if (!/^\d{10,30}$/.test(adsetId)) throw new Error("Existing ad set was not found");
  const creative = await graph(`${AD_ACCOUNT_ID}/adcreatives`, "POST", {
    name: `SpaPlus Qualified V2 ${key} 2026-08-15`,
    object_story_spec: JSON.stringify({
      page_id: PAGE_ID,
      link_data: {
        link,
        message,
        name: headline,
        description,
        image_hash: imageHash,
        call_to_action: { type: "SIGN_UP", value: { lead_gen_form_id: formId } },
      },
    }),
  });
  const creativeId = clean(creative.id);
  if (!/^\d{10,30}$/.test(creativeId)) throw new Error("Creative was not created");
  const ad = await graph(`${AD_ACCOUNT_ID}/ads`, "POST", {
    name: `SpaPlus Qualified Spa Businesses V2 ${key} 2026-08-15`,
    adset_id: adsetId,
    creative: JSON.stringify({ creative_id: creativeId }),
    status: "ACTIVE",
  });
  return { key, oldAdId: CURRENT_ADS[key], adsetId, creativeId, adId: clean(ad.id) };
}

async function testLead(input: Record<string, unknown>) {
  const formId = clean(input.formId);
  const key = clean(input.key) as MarketLanguage;
  if (!/^\d{10,30}$/.test(formId) || !(key in FORM_COPY)) throw new Error("Invalid test form");
  const province = key.startsWith("quebec") ? "Quebec" : "Ontario";
  const suffix = key.startsWith("quebec") ? "QC" : "ON";
  return graph(`${formId}/test_leads`, "POST", {
    field_data: JSON.stringify([
      { name: "spa_business_confirmation", values: ["confirmed_spa_business"] },
      { name: "company_name", values: [`SpaPlus ${suffix} Campaign Test Spa`] },
      { name: "phone_number", values: [key.startsWith("quebec") ? "+15145550181" : "+14165550182"] },
      { name: "full_name", values: [`SpaPlus ${suffix} Campaign Test`] },
      { name: "email", values: [`campaign-test-${suffix.toLowerCase()}@mail.spaplus.co`] },
      { name: "city", values: [key.startsWith("quebec") ? "Montreal" : "Toronto"] },
      { name: "province", values: [province] },
    ]),
  });
}

export async function POST(request: Request) {
  if (!authorized(request)) return Response.json({ error: "Unauthorized" }, { status: 401 });
  try {
    const body = (await request.json()) as { action?: string; input?: Record<string, unknown> };
    if (body.action === "inspect") return Response.json({ success: true, ...(await inspect()) });
    if (body.action === "create_form") {
      const key = clean(body.input?.key) as MarketLanguage;
      if (!(key in FORM_COPY)) throw new Error("Invalid form key");
      return Response.json({ success: true, key, result: await createForm(key) });
    }
    if (body.action === "upload_image") {
      const name = clean(body.input?.name);
      const bytes = clean(body.input?.bytes);
      if (!/^SPAPLUS_[A-Z_0-9-]+\.png$/.test(name) || bytes.length < 1000 || bytes.length > 12_000_000) throw new Error("Invalid image payload");
      return Response.json({ success: true, result: await graph(`${AD_ACCOUNT_ID}/adimages`, "POST", { name, bytes }) });
    }
    if (body.action === "create_ad") return Response.json({ success: true, result: await createAd(body.input || {}) });
    if (body.action === "pause_old_ads") {
      const results: Record<string, unknown> = {};
      for (const [key, adId] of Object.entries(CURRENT_ADS)) results[key] = await graph(adId, "POST", { status: "PAUSED" });
      return Response.json({ success: true, results });
    }
    if (body.action === "test_lead") return Response.json({ success: true, result: await testLead(body.input || {}) });
    throw new Error("Unsupported action");
  } catch (error: unknown) {
    console.error("Meta campaign admin action failed", { message: error instanceof Error ? error.message : "Unknown error" });
    return Response.json({ error: error instanceof Error ? error.message : "Meta campaign action failed" }, { status: 503 });
  }
}
